export const CONSTANTS = {
  ROUTE_FINDER_SEARCH: 'ROUTE_FINDER_SEARCH',
  ROUTE_FINDER: {
    NO_RESULTS: 'NO_RESULTS',
    INITIALISATION: 'INITIALISATION',
    SEARCH_RESULTS: 'SEARCH_RESULTS'
  }
}